### ISSUE TITLE
Include option to configure inclusion/exclusion of downstream models

### ISSUE THREAD

**Issue by dpguthrie** [dpguthrie/dbt-cloud-downstream-ci-action#2]
Right now, the command that's created for any downstream CI jobs includes any models that need to be run with the downstream operator `+`.  For example:

```
dbt build -s model_1+ ...
```

This may or may not be the desired behavior for the customer running this action, so the inclusion of the `+` operator should be an optional input to the action with a default of `True`.

**Comment by rchojn** [comment]
Hi @dpguthrie can I take this issue?

**Comment by dpguthrie** [comment]
@rchojn Please do! Thank you!
